language: bash
services:
- docker
script:
- "./test.sh"
after_success:
- "./after_success.sh"
env:
  global:
    secure: PjXQj/qmok9MWnyXh7/jUY5ObBFhoK/fkH+KBNArZcd0IJiVO50sBPVA5vPw9H5QEOLppJkE6QCPFeVGwidC8rh5R0B/GRtlLkws6o513D8mF+jn5ex7juonzkf8LtOjrxgXWvR7i/rBGJDe++UI6P0QFv1UU45tVA6r7jFMVTkSfm40OkmgtI4zIbBmrmf8UiuI5xPmyusfQ1IKEjgmfjTy8RrKAkHX5DZ4Inyc9GmbdcbviciBmdWcbqjBNa5lSjV3Ix0W6v9Z44WAuDCBodc9iZuogIFyOoZJzvvnC7S5Wg65wTtYM2OE47K7XHBe/rvpB7ktgKiaPnqsUHhxQeLvILOPSeYcAKJF7ND5mfJfMjk70FClQrOGkiw729CN3fLe9+ygp4Ma5pEgCdaFU8FKwEn4g+8uSzlAMict354fiTCT8TI3e5ShNTjQVJp0e7PwXl25MNwnbk7IOyyXLUpAyvzUvaqwmMV5rFtUNWPj59yjBtIXy5ctbePKBweDY5+tjRs43uFr/BkSE9mUBuk4OaLDqkzmXInHMWPJKB5rax+LJNCsNnWqYqE2f3yUvcDzZo7cVU11Q+M7NGM2KmDiPkma6GCPHxTgAv1x5aWgGcoB+7qpqbt70Nu9bPfbh3XFnEG1IW0se+swM9FEUxHYP+ySaziuAceH3JRALgE=
